---
AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation for deploying ecs-service

Parameters:
  LZStackPrefix:
    Description: 'Prefix to find values from landing zone'
    Type: String
  GitHubUser:
    Description: 'GitHub UserName'
    Type: 'String'
  GitRepo:
    Description: 'URL for Git repo'
    Type: 'String'
  GitBranch:
    Description: 'Branch being deployed'
    Type: 'String'
  GitHubToken:
    Description: 'OAuth Token for repo access'
    Type: 'String'
  ListenerPriority:
    Description: 'Priority in ALB'
    Type: Number
  ListenerPath:
    Description: 'Path on which Microservice is deployed'
    Type: 'String'
  ServiceName: # GitHubUser/GitRepo may have capital letters, need to send separately
    Description: 'Name of the service'
    Type: 'String'

Resources:
  PipelineIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${LZStackPrefix}-service-pipeline # Dynamic
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'codebuild:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                 # 'codecommit:BatchGetRepositories'
                 #  - 'codecommit:Get*'
                 #  - 'codecommit:GitPull'
                 #  - 'codecommit:List*'
                 #  - 'codecommit:Update*'
                 #  - 'codecommit:Test*'
                 #  - 'codecommit:UploadArchive'
                Effect: Allow
                Resource: '*'

  #TODO go into 'global' template
  BuildIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: 'codebuild.amazonaws.com'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ServiceName}

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: !Sub 'Checkout code from ${GitHubUser}/${GitRepo} and push to ECR at ${ContainerRepository}'
      Name: !Sub build-${ServiceName}-container
      ServiceRole: !Ref BuildIamRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login)
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
            build:
              commands:
                - docker build --tag "${REPOSITORY_URI}:${TAG}" .
            post_build:
              commands:
                - docker push "${REPOSITORY_URI}:${TAG}"
                - printf '{"tag":"%s"}' $TAG > build.json
                - aws s3 cp  s3://${TEMPLATE_BUCKET}/admin/ecs-workshop-service/cf-templates/common/microservice.yml .
          artifacts:
            files:
              - build.json
              - microservice.yml
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:1.12.1"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ContainerRepository}
          - Name: TEMPLATE_BUCKET
            Value:
              Fn::ImportValue: !Sub ${LZStackPrefix}-service-template-bucket
  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: !Sub '$Checkout container from ${ContainerRepository} and check response on port 80'
      Name: !Sub test-${ServiceName}-container
      ServiceRole: !Ref BuildIamRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login)
                - echo Testing $TAG
                - docker pull ${REPOSITORY_URI}:${TAG}
            build:
              commands:
                - docker run -d --rm --name test-container  ${REPOSITORY_NAME}:${TAG}
                - export CONTAINER_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test-container`
                - export STATUS_CODE=`curl -I http://$CONTAINER_IP:80/ 2>/dev/null | head -n 1|cut -d$' ' -f2`
                - ["$STATUS_CODE" eq "200"]
            post_build:
              commands:
                - docker kill test-container
          artifacts:
            files:
              - build.json
              - microservice.yml
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:1.12.1"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ContainerRepository}
          - Name: REPOSITORY_NAME
            Value: !Sub ${ContainerRepository}
          - Name: TAG
            Value:
              !GetParam:
                - BuildOutput
                - build.json
                - tag
  VanillaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${LZStackPrefix}-${ServiceName}-pipeline
      ArtifactStore:
        Location:
          Fn::ImportValue: !Sub ${LZStackPrefix}-service-artifact-bucket
        Type: 'S3'
      RoleArn: !GetAtt PipelineIamRole.Arn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: AppRepoSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitRepo
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: GitHubArtifact
              RunOrder: '1'
        -
          Name: ContainerBuild
          Actions:
            -
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub build-${ServiceName}-container
              InputArtifacts: [Name: 'GitHubArtifact']
              OutputArtifacts: [Name: 'BuildOutput']
              RunOrder: 1
        -
          Name: ContainerTest
          Actions:
            -
              Name: CodesTest
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub test-${ServiceName}-container
              InputArtifacts: [Name: 'BuildOutput']
              RunOrder: 1
        -
          Name: ServiceDeploy
          Actions:
            -
              Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub Deploy-${ServiceName}-Vanilla-On-${LZStackPrefix}
                ActionMode: CREATE_UPDATE
                RoleArn:
                  Fn::ImportValue: !Sub ${LZStackPrefix}-cloudformation-role-arn
                StackName: !Sub ${LZStackPrefix}-${ServiceName}-vanilla
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath:  BuildOutput::microservice.yml
                RoleArn: !GetAtt PipelineIamRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "ContainerRepository": "${ServiceName}",
                    "ContainerName": "${ServiceName}",
                    "ContainerTag": { "Fn::GetParam" : [ "BuildOutput", "build.json", "tag" ] },
                    "DesiredCount": "1",
                    "ListenerPriority": "${ListenerPriority}",
                    "ListenerPath": "${ListenerPath}",
                    "LZStackPrefix": "${LZStackPrefix}"
                  }
              InputArtifacts: [Name: 'BuildOutput']
